spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:11791/railway
    username: postgres
    password: ideYpANgZhBpxuXShXtOwJjXODMiHkyE
    name: tech-forb

  sql:
    init:
      mode: always # esto despues lo tengo que sacar

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000