spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB
  output:
    ansi:
      enabled: always

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
